# Site settings
baseurl = "https://bantin.github.io"
languageCode = "en-us"
sectionPagesMenu = "main"
theme = "frances"
pluralizelisttitles = false


[params]
	name = "Benjamin Antin Photography"
	description = "Photos for Racial Justice"
	email = "benjaminantin1@gmail.com"
	author = "Benjamin Antin"
